Use forked version of bootsnap
Avoid following error when running `bundle exec rake -P`

```
  :
rake aborted!

LoadError: cannot load such file -- thwait
.../vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:33:in `require'
.../vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
.../vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
.../vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
.../vendor/bundle/ruby/2.7.0/gems/sidekiq-scheduler-3.0.0/lib/sidekiq-scheduler/scheduler.rb:2:in `<top (required)>'
.../vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
.../vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
.../vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
.../vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
.../vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
.../vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
.../vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
.../vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
.../vendor/bundle/ruby/2.7.0/gems/sidekiq-scheduler-3.0.0/lib/sidekiq/scheduler.rb:1:in `<top (required)>'
.../vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
```