Add rexml gem
$ bundle exec rake -P
rake aborted!
LoadError: cannot load such file -- rexml/document
vendor/bundle/ruby/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require'
vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
vendor/bundle/ruby/3.0.0/gems/ruby-saml-1.11.0/lib/onelogin/ruby-saml/saml_message.rb:5:in `<top (required)>'